Translate 1 file to zh - tsconfig.json
microsoft/TypeScript-Website-Localizations pull request #70
Opened 2021-04-21 09:30 UTC by originalix

Files:
- tsconfig.json.md

2021-04-21 13:37 UTC, Kingwl commented
Thanks for the contribution! I'll take a look soon.

2021-04-23 06:10 UTC, Kingwl requested changes

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +根据你想要执行代码的 JavaScript 运行时环境，可能有一个基本配置，你可以参考[github.com/tsconfig/bases](https://github.com/tsconfig/bases/)来使用。
根据你要在其中运行代码的不同的 JavaScript 运行时环境，你可以在 [github.com/tsconfig/bases]() 上寻找一个合适的基本配置。你可以通过扩展这些已经处理过不同 JavaScript 运行时环境的 `tsconfig.json` 文件来简化你项目中的 tsconfig.json 。

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +<!-- 这些是你的项目扩展的""文件，它通过处理运行时支持简化你的“” -->
Should be removed?

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +举个例子，如果你的项目是基于 Node.js 12.x 写的，那么你可以使用 npm 依赖：[`@tsconfig/node12`](https://www.npmjs.com/package/@tsconfig/node12):
npm 模块

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +这使你的 `tsconfig.json` 专注在你自己选择的项目环境上，而不是所有的运行时环境。现在已经有了一些 tsconfig 基础配置，我们希望社区能够为不同的环境添加更多的内容。
专注在你的项目的目标环境上

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +这使你的 `tsconfig.json` 专注在你自己选择的项目环境上，而不是所有的运行时环境。现在已经有了一些 tsconfig 基础配置，我们希望社区能够为不同的环境添加更多的内容。
而不是所有可能的运行时环境

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +当`"compilerOptions"` 属性忽略的时候，会使用编译器的默认配置。请参考我们支持的[编译器选项](/tsconfig)列表
的时候 -> 时

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +当`"compilerOptions"` 属性忽略的时候，会使用编译器的默认配置。请参考我们支持的[编译器选项](/tsconfig)列表
列表`。`

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +## 模式
协议?

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +`tsconfig.json` 的模式可以在这里找到 [the JSON Schema Store](http://json.schemastore.org/tsconfig).
协议？

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +`tsconfig.json` 文件示例：
：

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +举个例子，如果你的项目是基于 Node.js 12.x 写的，那么你可以使用 npm 依赖：[`@tsconfig/node12`](https://www.npmjs.com/package/@tsconfig/node12):
：

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +## 模式
请访问[]() `。`

2021-04-23 06:10 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +`tsconfig.json` 的模式可以在这里找到 [the JSON Schema Store](http://json.schemastore.org/tsconfig).
`.` -> `。`

2021-04-23 06:11 UTC, Kingwl commented
@laosb PTAL.

2021-04-23 07:13 UTC, originalix commented
@Kingwl 😄 Thanks for code review. I've corrected all the questions.

2021-04-25 03:07 UTC, Kingwl commented on docs/documentation/zh/project-config/tsconfig.json.md
> +当`"compilerOptions"` 属性忽略时，会使用编译器的默认配置。请参考我们支持的[编译器选项](/tsconfig)列表。
> 属性忽略时

seems `当没有指定 compilerOptions 时` is better.

2021-04-25 05:56 UTC, originalix commented on docs/documentation/zh/project-config/tsconfig.json.md
> +当`"compilerOptions"` 属性忽略时，会使用编译器的默认配置。请参考我们支持的[编译器选项](/tsconfig)列表。
Done!

2021-04-25 06:07 UTC, Kingwl commented
Looks good. But I think we may need one more eye to review again.

2021-04-30 03:33 UTC, Kingwl commented
Seems there's no more eyes.
It's looks basically good. I think we could move on.

So

LGTM.

2021-04-30 03:33 UTC, merged

2021-04-30 08:18 UTC, orta commented
I can always ask for more Chinese readers on twitter?

2021-04-30 08:50 UTC, Kingwl commented
I'm planning seeking for help at some Chinese social network too.