docs(zh-Hans): translate `/handbook-v2/Type Manipulation/Conditional Types.md` to Chinese
microsoft/TypeScript-Website-Localizations pull request #93
Opened 2021-07-04 10:41 UTC by htmlin

2021-07-30 10:31 UTC, Kingwl requested changes
Thanks for the contribution! Some minor issues.

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +在本例中，TypeScript 错误是因为 `T` 不知道有一个名为 `message` 的属性。
产生错误是因为不知道 T 有一个名为 message 的属性

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +然而，如果我们希望 `MessageOf` 采用任何类型，并且在 `message` 属性不可用的情况下缺省为 `never` 之类的类型，该怎么办呢？
默认为。

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +然而，如果我们希望 `MessageOf` 采用任何类型，并且在 `message` 属性不可用的情况下缺省为 `never` 之类的类型，该怎么办呢？
接受任何类型

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +然而，如果我们希望 `MessageOf` 采用任何类型，并且在 `message` 属性不可用的情况下缺省为 `never` 之类的类型，该怎么办呢？
我们应该怎么做呢？

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +我们只是发现自己使用条件类型来应用约束，然后提取出类型。
只是 -> 删掉

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +当从具有多个调用签名的类型（如重载函数的类型）进行推断时，将从 _最后一个_ 签名进行推断（这大概是最允许的捕获所有的情况）。无法基于参数类型列表执行重载解析。
这也许是最宽松的万能情况

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +当从具有多个调用签名的类型（如重载函数的类型）进行推断时，将从 _最后一个_ 签名进行推断（这大概是最允许的捕获所有的情况）。无法基于参数类型列表执行重载解析。
重载决议

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +如果我们将联合类型插入 `ToArray`，则条件类型将应用于该联合类型的每个成员。
传入

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +当条件类型作用于泛型类型时，它们在给定联合类型时成为 _分配类型_ 。
当传入的类型参数为联合类型时，他们会被“分配”

2021-07-30 10:31 UTC, Kingwl commented on docs/documentation/zh/handbook-v2/Type Manipulation/Conditional Types.md
> +所以我们只剩下：
所以我们得到

2021-08-01 07:06 UTC, htmlin commented on docs/documentation/zh/handbook-v2/Everyday Types.md
> +title: 日常类型
```suggestion
title: 常见类型
```

2022-07-14 07:02 UTC, Kingwl commented
LGTM

2022-07-14 07:03 UTC, merged